# Upgrades gradle automatically to furthest working version

name: Upgrade Gradle CI

on:
  push:
    branches: [ master ]

jobs:
  check-version-upgrade:
    env:
     upgrade-version: 7.0.2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Set local version
      id: gversion
      run: echo "::set-output name=local::$(./gradlew --version | grep -oP '(?<=Gradle ).*' | tr -d '!')"
    - name: Upgrade
      if: ${{steps.gversion.outputs.local != env.upgrade-version}}
      run: |          
          ./gradlew wrapper --gradle-version ${{ env.upgrade-version }}
          ./gradlew wrapper --gradle-version ${{ env.upgrade-version }}
    - name: Check build
      if: ${{steps.gversion.outputs.local != env.upgrade-version}}
      run: |
          ./gradlew clean build
    - name: Push succesful upgrade
      if: ${{steps.gversion.outputs.local != env.upgrade-version}}
      run: |
          git config --global user.name 'Homer Simpson'
          git config --global user.email 'alisher.urunov@accenture.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated Gradle Upgrade"
          git push
